[build]
  publish = "."

[functions]
  directory = "functions"          # <- tu carpeta real de Functions
  node_bundler = "esbuild"
  included_files = [
    "docs/**",                     # <- empaqueta PDFs dentro del zip de la Function
    "data/**"                      # <- empaqueta embeddings.json
  ]