[build]
  command = "node scripts/build-embeddings.mjs"
  publish = "dist"

[functions]
  # IMPORTANTE: tu carpeta real es "functions"
  directory = "functions"
  node_bundler = "esbuild"

# Incluir los archivos que necesita la función "chat"
[functions."chat"]
  included_files = ["data/**", "docs/**"]

# (opcional) SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200