[build]
  command = "npm install && npm run build-embeddings"
  publish = "."

[functions]
  node_bundler = "esbuild"
  included_files = ["data/*"]

# Ocultar /data del público (el índice es solo para la función)
[[redirects]]
  from = "/data/*"
  to = "/404.html"
  status = 404