[build]
  command = "npm install --no-audit --no-fund"
  publish = "."

[functions]
  directory = "functions"
  node_bundler = "esbuild"
  included_files = ["data/**", "docs/**"]

[build.environment]
  NODE_VERSION = "18"