[build]
  command = "npm install && npm run build-embeddings"
  publish = "."

[functions]
  directory = "functions"
  node_bundler = "esbuild"
  included_files = ["data/*"]

[[redirects]]
  from = "/data/*"
  to = "/404.html"
  status = 404

