[build]
  publish = "."
  command = "npm install && npm run build:emb"

[build.environment]
  NODE_VERSION = "18"

[functions]
  directory = "functions"
  node_bundler = "esbuild"
  included_files = [
    "docs/**",
    "data/**"
  ]