[build]
  command = "npm install --no-audit --no-fund && node scripts/build-embeddings.mjs"
  publish = "."
  environment = { NODE_VERSION = "20" }

[functions]
  node_bundler = "esbuild"
  included_files = ["docs/**", "data/**"]

# 🔽 esta regla es la clave para /api/*
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/chat"
  status = 200
  force = true