[build]
  # Si usás un script para generar embeddings, dejalo aquí.
  command = "node scripts/build-embeddings.js"
  publish = "dist"

# Es importante declarar el bundler y el directorio de funciones.
[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

# Incluir los assets SOLO para la función "chat"
[functions."chat"]
  included_files = ["data/**", "docs/**", "documentos/**"]

# (Opcional) otras redirecciones de tu app
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200