[build]
  publish = "."
  command = "npm install && npm run build:emb"   # genera data/embeddings.json en el deploy

[build.environment]
  NODE_VERSION = "18"

[functions]
  directory = "functions"        # tu carpeta real
  node_bundler = "esbuild"
  included_files = [
    "docs/**",                   # empaqueta PDFs
    "data/**"                    # empaqueta embeddings.json generado
  ]